# Generated by Django 3.1.7 on 2021-04-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city', models.CharField(max_length=22)),
                ('city_ascii', models.CharField(max_length=22, null=True)),
                ('latitude', models.CharField(max_length=22, null=True)),
                ('longitude', models.CharField(max_length=22, null=True)),
                ('country', models.CharField(max_length=22, null=True)),
                ('iso2', models.CharField(max_length=22, null=True)),
                ('iso3', models.CharField(max_length=22, null=True)),
                ('admin', models.CharField(max_length=22, null=True)),
                ('capital', models.CharField(max_length=22, null=True)),
                ('population', models.CharField(max_length=22, null=True)),
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
            ],
        ),
    ]
