# Generated by Django 3.1.7 on 2021-04-09 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combo', '0002_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='language',
        ),
    ]
